language: go

# use container infrastructure
sudo: false

# cache go build cache and pkg mod
cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

go:
  - "1.10.x"

# have an empty install to avoid travis doing a go get
install: []
